apiVersion: v1
data:  
  Dockerfile: |                 
    FROM golang:1-alpine as builder
    
    WORKDIR /app
    COPY curielogger .
    RUN go build -o build/curielogger ./cmd/grpc

    FROM alpine
    RUN apk update && apk add ca-certificates curl bash apache2-utils && rm -rf /var/cache/apk/*           
    RUN mkdir -p /etc/curielogger/                                              
    COPY contrib /contrib                                  
    COPY --from=builder /app/build/curielogger /bin                         
    COPY --from=builder /app/curielogger.yml /etc/curielogger/                                                   
    ENTRYPOINT ["/bin/curielogger"]
 
kind: ConfigMap
metadata:            
  creationTimestamp: "2021-07-26T07:03:15Z"  
  managedFields:                            
  - apiVersion: v1  
    fieldsType: FieldsV1                  
    fieldsV1:                        
      f:data:
        .: {}        
        f:Dockerfile: {}             
        manager: kubectl-create                        
        operation: Update                               
        time: "2021-07-26T07:03:15Z"                         
        name: curielogger                                    
        namespace: default                         
        resourceVersion: "1545412"                          
        uid: 349213f7-93cb-497e-8cd3-3d334ab039ea
