---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ws-app
spec:
  selector:
    matchLabels:
      run: nginx-ws-app
  replicas: 3 # Update the replicas from 2 to 3
  template:
    metadata:
      labels:
        run: nginx-ws-app
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
        - name: nginx-webserver
          image: nginx:stable # upgrade from nginx:1.21
          ports:
            - containerPort: 443
            - containerPort: 8080
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/nginx/ssl
            - name: configmap-volume
              mountPath: /etc/nginx/conf.d
        - name: weather-app
          image: adamakeinan/weather-app 
          ports:
            - containerPort: 3005     
        
