apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: service-prometheus
  name: service-prometheus
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: service-prometheus
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']  
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']    
