---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ws-app
  labels:
    run: nginx-ws-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: nginx-ws-app
