apiVersion: v1
kind: Service
metadata:
  name: nginx-cs-svc
spec:
  selector:
    role: cs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cs-app
  labels:
    role: cs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: cs-app
  template:
    metadata:
      labels:
        role: cs-app
    spec:
      containers:
      - name: cs-app
        image: adamkeinan/counter-service
